### ISSUE TITLE
Activity theme not applied into child views

### ISSUE THREAD

**Issue by gumil** [nhaarman/acorn#150] opened 2019-09-16 09:22 UTC
**Activity theme not applied into child views**
Child views does not inherit activity theme might be because `setContentView` is not called.

**To Reproduce**
I have created all views programmatically and does not depend on XML.
Issues found so far:
1. Child views did not inherit colors from theme
2. `selectableItemBackground` does not resolve ripple animation since it does not get the right theme.

**Expected behavior**
Activity theme should be applied into child views

**Environmental info (please complete the following information):**
 - Library version: 1.0.0
 - Device: Pixel 3 x86 emulator
 - OS: Android 10

**Comment by nhaarman** [comment] 2019-09-16 09:37
Could you provide some sample code of how you're creating the views? 

Note that views should be created using the `Activity` context which contains the proper theme, and when not created from XML you should pass the proper `defStyleAttr` to the View's constructor (e.g. `android.R.attr.textViewStyle` for `TextView`).

Whether or not `setContentView` is used should not play any role here.

**Comment by gumil** [comment] 2019-09-16 09:55
Views are created using `ViewProvidingScene`'s `createViewController` parent context parameter. The colors were not inherited like `colorPrimary` when Acorn was used. But setting the view directly to `setContentView` it got the right colors.

**Comment by nhaarman** [comment] 2019-09-16 11:08
Are you using `AcornAppCompatActivity`?

**Comment by gumil** [comment] 2019-09-16 11:25
Yes, and I am relying to the `colorPrimary` etc.

**Comment by nhaarman** [comment] 2019-09-16 11:44
Hm, this should work actually. The [`parent: ViewGroup` provided in `ViewProvidingScene`](https://github.com/nhaarman/acorn/blob/1.x/ext/acorn-android/src/main/java/com/nhaarman/acorn/android/presentation/ViewProvidingScene.kt#L57) is derived from the `FrameLayout` provided by the system through [`android.R.id.content`](https://github.com/nhaarman/acorn/blob/1.x/ext/acorn-android/acorn-android-appcompat/src/main/java/com/nhaarman/acorn/android/AcornAppCompatActivity.kt#L99), which obviously contains the theme info as necessary.

`Activity.setContentView` delegates to [`PhoneWindow.setContentView`](https://android.googlesource.com/platform/frameworks/base/+/696cba573e651b0e4f18a4718627c8ccecb3bda0/policy/src/com/android/internal/policy/impl/PhoneWindow.java#218), which [uses the same Activity `context` instance](https://android.googlesource.com/platform/frameworks/base/+/696cba573e651b0e4f18a4718627c8ccecb3bda0/policy/src/com/android/internal/policy/impl/PhoneWindow.java#182) as provided through the `parent` instance, so there's no further magic happening there to make themes work.

Without a reproducible example there's not really much to go on from here. Would it be possible to create a sample project that consistently reproduces the issue?

**Comment by gumil** [comment] 2019-09-16 17:16
With Acorn Scenes:
![Screenshot_1568651983](https://user-images.githubusercontent.com/6756250/64976412-7ed1cb00-d8b1-11e9-83d2-dadb354cdc7c.png)

```kotlin
class MainActivity : AcornAppCompatActivity() {
    override fun provideNavigatorProvider(): NavigatorProvider {
        return DemoNavigatorProvider
    }
}
```

setContentView:
![Screenshot_1568652005](https://user-images.githubusercontent.com/6756250/64976413-7ed1cb00-d8b1-11e9-8be5-565f60d4bc9c.png)

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(HomeView(this, DemoModel.values().toList()))
    }
}
```

The whole code is here https://github.com/gumil/acorn-demo

**Comment by nhaarman** [comment] 2019-09-16 17:19
Thanks! That should help a lot.

**Comment by nhaarman** [comment] 2019-09-16 17:55
The issue is more easily reproduced like so:

```kotlin
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //setContentView(TextView(this).apply { text = "HELLO WORLD" })
        setContentView(TextView(findViewById<ViewGroup>(R.id.content).context).apply { text = "HELLO WORLD" })
    }
}
```

The assumption I made earlier is that the `Context` passed was the _same_ instance in both cases seems to be wrong: the second instance (from the `android.R.id.content` View) is a `ContextThemeWrapper`.
The `baseContext` of this wrapper _is_ in fact the `MainActivity` instance, so this 'fixes' the theming issue again:

```kotlin
 val context = (findViewById<ViewGroup>(R.id.content).context as ContextThemeWrapper).baseContext
 setContentView(TextView(context).apply { text = "HELLO WORLD" })
```

**Comment by nhaarman** [comment] 2019-09-16 18:39
It seems AppCompat does some hacky things under the hood, by removing the `android.R.id.content` id from the original View and applying it to its own view: 

https://android.googlesource.com/platform/frameworks/support/+/d25af35/v7/appcompat/src/android/support/v7/app/AppCompatDelegateImplV7.java#390

```java
// Change our content FrameLayout to use the android.R.id.content id.
// Useful for fragments.
decorContent.setId(View.NO_ID);
abcContent.setId(android.R.id.content);
```

This `abcContent` View [is created](https://android.googlesource.com/platform/frameworks/support/+/d25af35/v7/appcompat/src/android/support/v7/app/AppCompatDelegateImplV7.java#323) using an ['emulated' `ContextThemeWrapper`](https://android.googlesource.com/platform/frameworks/support/+/d25af35/v7/appcompat/src/android/support/v7/app/AppCompatDelegateImplV7.java#292):

```java
/**
--
* This needs some explanation. As we can not use the android:theme attribute
* pre-L, we emulate it by manually creating a LayoutInflater using a
* ContextThemeWrapper pointing to actionBarTheme.
*/
TypedValue outValue = new TypedValue();
mContext.getTheme().resolveAttribute(R.attr.actionBarTheme, outValue, true);
themedContext = new ContextThemeWrapper(mContext, outValue.resourceId);
```

This `ContextThemeWrapper` is the instance we're seeing in our issue here, which resolves to the `ActionBarTheme` and not the app's theme..

I'm not sure yet why `LayoutInflater.from` that `ContextThemeWrapper` uses proper theming though (which is why I haven't seen this issue before).

**Comment by nhaarman** [comment] 2019-09-16 18:43
A quick-and-dirty fix could be to insert a `FrameLayout` in between with the proper `Context` instance like so:

```kotlin
class MainActivity : AcornAppCompatActivity() {

    private lateinit var rootView: ViewGroup

    override fun onCreate(savedInstanceState: Bundle?) {
        rootView = FrameLayout(this)
        setContentView(rootView)
        super.onCreate(savedInstanceState)
    }

    override fun provideNavigatorProvider(): NavigatorProvider {
        return DemoNavigatorProvider
    }

    override fun provideRootView(): ViewGroup {
        return rootView
    }
}
```

I'll see and find if there's a 'proper' fix for this, or if something like this will be included in `AcornAppCompatActivity`.

**Comment by gumil** [comment] 2019-09-16 19:08
Thank you for further investigating this!

I think this workaround works. Seems also like an edge case since I am just experimenting on `Acorn` and programmatic views with `Contour`. I just have this idea that when `Jetpack Compose` is released, programmatic views will be more common.

**Comment by nhaarman** [comment] 2019-09-17 07:22
Yeah it's a basic case that really should work though. Thanks again for the repro!

**Comment by nhaarman** [comment] 2019-09-27 11:52
An investigative issue on the android tracker: https://issuetracker.google.com/issues/141726320

**Closed as completed** 2019-09-29 13:34 UTC
Labels: type:bug, priority:high

**Comment by manueldidonna** [comment] 2019-10-23 10:38
I tried to support the night mode into my app using DayNight theme from Material Components & a proper set of colors with night qualifier (I've done the same thing in another app). 

Child views continue to use the light theme attributes (so black text color,  etc..) but I tried to explicitly use the color set overwritten by the night mode (`Context.getColor(resId)`) and they are correctly imported

**Comment by manueldidonna** [comment] 2019-10-23 14:32
Update#1: my custom attributes or the ones explicitly declared in my DayNight theme (colorPrimary,  colorsurface, etc ..) are correctly resolved. Problems come from android framework attributes (textColorPrimary, selectableItemBackground, listDivider, toolbar attributes)
